using System.Text;
using Mythetech.Framework.AI.Generator.Models;
using Mythetech.Framework.AI.Generator.Utilities;

namespace Mythetech.Framework.AI.Generator.Emitters;

/// <summary>
/// Generates MCP tool classes from tool metadata.
/// Each command/query generates a separate MCP tool class that routes through MessageBus.
/// </summary>
internal static class McpToolEmitter
{
    /// <summary>
    /// Generates an MCP tool class for a single command/query.
    /// </summary>
    public static string GenerateMcpTool(ToolMetadata tool)
    {
        var sb = new StringBuilder();
        var hasParameters = tool.Parameters.Count > 0;
        var inputClassName = $"{tool.TypeName}McpInput";
        var toolClassName = $"{tool.TypeName}McpTool";

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Mythetech.Framework.Infrastructure.Mcp;");
        sb.AppendLine("using Mythetech.Framework.Infrastructure.MessageBus;");
        sb.AppendLine($"using {tool.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"namespace {tool.Namespace}.Generated;");
        sb.AppendLine();

        if (hasParameters)
        {
            GenerateInputDto(sb, tool, inputClassName);
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// MCP tool for {tool.ToolName}.");
        sb.AppendLine("/// Auto-generated by Mythetech.Framework.AI.Generator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"[McpTool(Name = \"{tool.ToolName}\", Description = \"{EscapeString(tool.Description)}\")]");

        if (hasParameters)
        {
            sb.AppendLine($"public sealed class {toolClassName} : IMcpTool<{inputClassName}>");
        }
        else
        {
            sb.AppendLine($"public sealed class {toolClassName} : IMcpTool");
        }

        sb.AppendLine("{");
        sb.AppendLine("    private readonly IMessageBus _messageBus;");
        sb.AppendLine();
        sb.AppendLine($"    public {toolClassName}(IMessageBus messageBus)");
        sb.AppendLine("    {");
        sb.AppendLine("        _messageBus = messageBus;");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (hasParameters)
        {
            GenerateTypedExecuteMethod(sb, tool, inputClassName);
        }
        else
        {
            GenerateUntypedExecuteMethod(sb, tool);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the AddGeneratedMcpTools registration extension.
    /// </summary>
    public static string GenerateRegistration(List<string> toolClassNames, List<string> toolNamespaces)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var ns in toolNamespaces.Distinct())
        {
            sb.AppendLine($"using {ns}.Generated;");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Mythetech.Framework.AI.Generator.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering generated MCP tools.");
        sb.AppendLine("/// Auto-generated by Mythetech.Framework.AI.Generator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class McpToolRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds all generated MCP tools to the service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddGeneratedMcpTools(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var className in toolClassNames)
        {
            sb.AppendLine($"        services.AddTransient<{className}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateInputDto(StringBuilder sb, ToolMetadata tool, string inputClassName)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Input parameters for {tool.ToolName} MCP tool.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {inputClassName}");
        sb.AppendLine("{");

        foreach (var param in tool.Parameters)
        {
            var propertyName = NamingConventions.ToPascalCase(param.Name);
            var requiredStr = param.IsRequired ? "true" : "false";
            var description = string.IsNullOrEmpty(param.Description)
                ? $"The {param.Name} parameter"
                : param.Description;

            sb.AppendLine($"    [McpToolInput(Description = \"{EscapeString(description)}\", Required = {requiredStr})]");
            sb.AppendLine($"    public {param.TypeName} {propertyName} {{ get; set; }}{GetDefaultInitializer(param)}");

            if (param != tool.Parameters[tool.Parameters.Count - 1])
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
    }

    private static void GenerateTypedExecuteMethod(StringBuilder sb, ToolMetadata tool, string inputClassName)
    {
        sb.AppendLine($"    public async Task<McpToolResult> ExecuteAsync({inputClassName} input, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        var constructorArgs = string.Join(", ",
            tool.Parameters.Select(p => $"input.{NamingConventions.ToPascalCase(p.Name)}"));

        if (tool.IsQuery)
        {
            sb.AppendLine($"        var query = new {tool.TypeName}({constructorArgs});");
            sb.AppendLine($"        var result = await _messageBus.SendAsync<{tool.TypeName}, {tool.ResponseTypeName}>(query);");
            sb.AppendLine("        return McpToolResult.Text(result.ToString());");
        }
        else
        {
            sb.AppendLine($"        var command = new {tool.TypeName}({constructorArgs});");
            sb.AppendLine("        await _messageBus.PublishAsync(command);");
            sb.AppendLine($"        return McpToolResult.Text(\"Command '{tool.ToolName}' executed successfully.\");");
        }

        sb.AppendLine("    }");
    }

    private static void GenerateUntypedExecuteMethod(StringBuilder sb, ToolMetadata tool)
    {
        sb.AppendLine("    public async Task<McpToolResult> ExecuteAsync(object? input, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");

        if (tool.IsQuery)
        {
            sb.AppendLine($"        var query = new {tool.TypeName}();");
            sb.AppendLine($"        var result = await _messageBus.SendAsync<{tool.TypeName}, {tool.ResponseTypeName}>(query);");
            sb.AppendLine("        return McpToolResult.Text(result.ToString());");
        }
        else
        {
            sb.AppendLine($"        var command = new {tool.TypeName}();");
            sb.AppendLine("        await _messageBus.PublishAsync(command);");
            sb.AppendLine($"        return McpToolResult.Text(\"Command '{tool.ToolName}' executed successfully.\");");
        }

        sb.AppendLine("    }");
    }

    private static string GetDefaultInitializer(ParameterMetadata param)
    {
        if (param.TypeName.EndsWith("?"))
            return " = null!;";

        if (param.TypeName == "string")
            return " = string.Empty;";

        if (IsValueType(param.TypeName))
            return "";

        return " = default!;";
    }

    private static bool IsValueType(string typeName)
    {
        var baseType = typeName.TrimEnd('?');
        return baseType switch
        {
            "int" or "long" or "short" or "byte" or "sbyte" => true,
            "uint" or "ulong" or "ushort" => true,
            "float" or "double" or "decimal" => true,
            "bool" => true,
            "char" => true,
            "System.Int32" or "System.Int64" or "System.Int16" => true,
            "System.Byte" or "System.SByte" => true,
            "System.UInt32" or "System.UInt64" or "System.UInt16" => true,
            "System.Single" or "System.Double" or "System.Decimal" => true,
            "System.Boolean" => true,
            "System.Char" => true,
            _ => false
        };
    }

    private static string EscapeString(string s)
    {
        return s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r");
    }
}
