version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "Mythetech.Hermes"
      - dependency-name: "Mythetech.Hermes.*"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
